#!/bin/bash
echo "=== Veth Egress Path Test ==="
echo -e "\n1. Checking veth pair..."
ip link show veth_voq_in 2>/dev/null && echo "✓ veth_voq_in exists" || echo "✗ veth_voq_in missing"
ip link show veth_voq_out 2>/dev/null && echo "✓ veth_voq_out exists" || echo "✗ veth_voq_out missing"
echo -e "\n2. Checking XDP on veth_voq_out..."
ip link show veth_voq_out | grep -q "xdp" && echo "✓ XDP attached" || echo "✗ XDP not attached"
echo -e "\n3. Checking VOQd process..."
pgrep -x rswitch-voqd > /dev/null && echo "✓ VOQd running (PID: $(pgrep -x rswitch-voqd))" || echo "✗ VOQd not running"
echo -e "\n4. Veth egress statistics:"
sudo bpftool map dump name veth_egress_stats 2>/dev/null || echo "Map not found"
echo -e "\n5. VOQd statistics (last 20 lines):"
sudo tail -20 /tmp/rswitch-voqd.log 2>/dev/null || echo "Log not found"
echo -e "\n=== Test Complete ==="